# Site settings
email: thomas.vaeth@gmail.com

# SEO settings
title: Thomas Vaeth
description: Thomas Vaeth is a Web Developer at Urban Influence in Seattle, Washington.
url: "http://thomasvaeth.com"
twitter_username: thomasvaeth
default_img: https://source.unsplash.com/qHblAFPy2uU/2000x1200

# Build settings
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
permalink: pretty

# Sass
sass:
  style: compressed

# Gems
gems: [octopress-autoprefixer]
