# Site settings
email: thomas.vaeth@gmail.com

# SEO settings
title: Thomas Vaeth
description: Thomas Vaeth is a Software Engineer at Getty Images in Seattle, Washington.
url: http://thomasvaeth.com
twitter_username: thomasvaeth
default_img: http://thomasvaeth.com/assets/images/me.jpg

# Build settings
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
permalink: pretty

# Sass
sass:
  style: compressed

# Gems
gems: [octopress-autoprefixer]
