# Site/SEO settings
email: thomas.vaeth@gmail.com
paginate: 12
paginate_path: /articles/page/:num
permalink: /articles/:year/:month/:day/:title
google_analytics: UA-57782903-1

name: Thomas Vaeth
title: Thomas Vaeth
description: >
  Thomas Vaeth is a Software Engineer at Getty Images in Seattle, Washington.
url: http://thomasvaeth.com
twitter_username: thomasvaeth
default_img: http://thomasvaeth.com/assets/images/me.jpg

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

# Collections
collections:
  work:
    output: true
    permalink: /work/:path
